name = "meu-projeto"
type = "javascript"

account_id = "b5af72cc1931a93ffea791b173a583a6"
workers_dev = true

[site]
bucket = "./dist"  # Certifique-se de que a pasta está correta

[build]
command = "npm run build"  # Comando para construir seu projeto
